version: '3.1'

services:

  redmine:
    image: redmine:latest
    restart: always
    ports:
      - 8080:3000
    volumes:
      - ./:/usr/src/redmine/public/themes/didiez
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine